/*
 * This file is part of the Buildings and Habitats object Model (BHoM)
 * Copyright (c) 2015 - 2024, the respective contributors. All rights reserved.
 *
 * Each contributor holds copyright over their respective contributions.
 * The project versioning (Git) records all such contribution source information.
 *                                           
 *                                                                              
 * The BHoM is free software: you can redistribute it and/or modify         
 * it under the terms of the GNU Lesser General Public License as published by  
 * the Free Software Foundation, either version 3.0 of the License, or          
 * (at your option) any later version.                                          
 *                                                                              
 * The BHoM is distributed in the hope that it will be useful,              
 * but WITHOUT ANY WARRANTY; without even the implied warranty of               
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the                 
 * GNU Lesser General Public License for more details.                          
 *                                                                            
 * You should have received a copy of the GNU Lesser General Public License     
 * along with this code. If not, see <https://www.gnu.org/licenses/lgpl-3.0.html>.      
 */

using Autodesk.Revit.DB;
using BH.Engine.Adapters.Revit;
using BH.oM.Adapters.Revit.Settings;
using BH.oM.Base;
using BH.oM.Physical.Elements;
using BH.oM.Physical.FramingProperties;
using BH.oM.Base.Attributes;
using System.Collections.Generic;
using System.ComponentModel;

namespace BH.Revit.Engine.Core
{
    public static partial class Convert
    {
        /***************************************************/
        /****               Public Methods              ****/
        /***************************************************/

        [Description("Converts a Revit FamilyInstance to BH.oM.Physical.Elements.Bracing.")]
        [Input("familyInstance", "Revit FamilyInstance to be converted.")]
        [Input("settings", "Revit adapter settings to be used while performing the convert.")]
        [Input("refObjects", "Optional, a collection of objects already processed in the current adapter action, stored to avoid processing the same object more than once.")]
        [Output("bracing", "BH.oM.Physical.Elements.Bracing resulting from converting the input Revit FamilyInstance.")]
        public static Bracing BracingFromRevit(this FamilyInstance familyInstance, RevitSettings settings = null, Dictionary<string, List<IBHoMObject>> refObjects = null)
        {
            settings = settings.DefaultIfNull();

            Bracing bracing = refObjects.GetValue<Bracing>(familyInstance.Id);
            if (bracing != null)
                return bracing;

            oM.Geometry.ICurve locationCurve = familyInstance.LocationCurveFraming(settings);
            IFramingElementProperty property = familyInstance.FramingElementProperty(settings, refObjects);
            bracing = BH.Engine.Physical.Create.Bracing(locationCurve, property);

            //Set identifiers, parameters & custom data
            bracing.SetIdentifiers(familyInstance);
            bracing.CopyParameters(familyInstance, settings.MappingSettings);
            bracing.SetProperties(familyInstance, settings.MappingSettings);

            refObjects.AddOrReplace(familyInstance.Id, bracing);
            return bracing;
        }

        /***************************************************/
    }
}




